version: '3.1'

services:
  pg:
    image: postgres:14-alpine
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=100'
      - '-c'
      - 'shared_buffers=256MB'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdf1234
      POSTGRES_DB: nerdmoney
    ports:
      - 5432:5432
